package com.lp.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class LfucCustManagerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public LfucCustManagerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCmNoIsNull() {
            addCriterion("CM_NO is null");
            return (Criteria) this;
        }

        public Criteria andCmNoIsNotNull() {
            addCriterion("CM_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCmNoEqualTo(String value) {
            addCriterion("CM_NO =", value, "cmNo");
            return (Criteria) this;
        }

        public Criteria andCmNoNotEqualTo(String value) {
            addCriterion("CM_NO <>", value, "cmNo");
            return (Criteria) this;
        }

        public Criteria andCmNoGreaterThan(String value) {
            addCriterion("CM_NO >", value, "cmNo");
            return (Criteria) this;
        }

        public Criteria andCmNoGreaterThanOrEqualTo(String value) {
            addCriterion("CM_NO >=", value, "cmNo");
            return (Criteria) this;
        }

        public Criteria andCmNoLessThan(String value) {
            addCriterion("CM_NO <", value, "cmNo");
            return (Criteria) this;
        }

        public Criteria andCmNoLessThanOrEqualTo(String value) {
            addCriterion("CM_NO <=", value, "cmNo");
            return (Criteria) this;
        }

        public Criteria andCmNoLike(String value) {
            addCriterion("CM_NO like", value, "cmNo");
            return (Criteria) this;
        }

        public Criteria andCmNoNotLike(String value) {
            addCriterion("CM_NO not like", value, "cmNo");
            return (Criteria) this;
        }

        public Criteria andCmNoIn(List<String> values) {
            addCriterion("CM_NO in", values, "cmNo");
            return (Criteria) this;
        }

        public Criteria andCmNoNotIn(List<String> values) {
            addCriterion("CM_NO not in", values, "cmNo");
            return (Criteria) this;
        }

        public Criteria andCmNoBetween(String value1, String value2) {
            addCriterion("CM_NO between", value1, value2, "cmNo");
            return (Criteria) this;
        }

        public Criteria andCmNoNotBetween(String value1, String value2) {
            addCriterion("CM_NO not between", value1, value2, "cmNo");
            return (Criteria) this;
        }

        public Criteria andCmNameIsNull() {
            addCriterion("CM_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCmNameIsNotNull() {
            addCriterion("CM_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCmNameEqualTo(String value) {
            addCriterion("CM_NAME =", value, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameNotEqualTo(String value) {
            addCriterion("CM_NAME <>", value, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameGreaterThan(String value) {
            addCriterion("CM_NAME >", value, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameGreaterThanOrEqualTo(String value) {
            addCriterion("CM_NAME >=", value, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameLessThan(String value) {
            addCriterion("CM_NAME <", value, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameLessThanOrEqualTo(String value) {
            addCriterion("CM_NAME <=", value, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameLike(String value) {
            addCriterion("CM_NAME like", value, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameNotLike(String value) {
            addCriterion("CM_NAME not like", value, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameIn(List<String> values) {
            addCriterion("CM_NAME in", values, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameNotIn(List<String> values) {
            addCriterion("CM_NAME not in", values, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameBetween(String value1, String value2) {
            addCriterion("CM_NAME between", value1, value2, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmNameNotBetween(String value1, String value2) {
            addCriterion("CM_NAME not between", value1, value2, "cmName");
            return (Criteria) this;
        }

        public Criteria andCmPwdIsNull() {
            addCriterion("CM_PWD is null");
            return (Criteria) this;
        }

        public Criteria andCmPwdIsNotNull() {
            addCriterion("CM_PWD is not null");
            return (Criteria) this;
        }

        public Criteria andCmPwdEqualTo(String value) {
            addCriterion("CM_PWD =", value, "cmPwd");
            return (Criteria) this;
        }

        public Criteria andCmPwdNotEqualTo(String value) {
            addCriterion("CM_PWD <>", value, "cmPwd");
            return (Criteria) this;
        }

        public Criteria andCmPwdGreaterThan(String value) {
            addCriterion("CM_PWD >", value, "cmPwd");
            return (Criteria) this;
        }

        public Criteria andCmPwdGreaterThanOrEqualTo(String value) {
            addCriterion("CM_PWD >=", value, "cmPwd");
            return (Criteria) this;
        }

        public Criteria andCmPwdLessThan(String value) {
            addCriterion("CM_PWD <", value, "cmPwd");
            return (Criteria) this;
        }

        public Criteria andCmPwdLessThanOrEqualTo(String value) {
            addCriterion("CM_PWD <=", value, "cmPwd");
            return (Criteria) this;
        }

        public Criteria andCmPwdLike(String value) {
            addCriterion("CM_PWD like", value, "cmPwd");
            return (Criteria) this;
        }

        public Criteria andCmPwdNotLike(String value) {
            addCriterion("CM_PWD not like", value, "cmPwd");
            return (Criteria) this;
        }

        public Criteria andCmPwdIn(List<String> values) {
            addCriterion("CM_PWD in", values, "cmPwd");
            return (Criteria) this;
        }

        public Criteria andCmPwdNotIn(List<String> values) {
            addCriterion("CM_PWD not in", values, "cmPwd");
            return (Criteria) this;
        }

        public Criteria andCmPwdBetween(String value1, String value2) {
            addCriterion("CM_PWD between", value1, value2, "cmPwd");
            return (Criteria) this;
        }

        public Criteria andCmPwdNotBetween(String value1, String value2) {
            addCriterion("CM_PWD not between", value1, value2, "cmPwd");
            return (Criteria) this;
        }

        public Criteria andCmMobileIsNull() {
            addCriterion("CM_MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andCmMobileIsNotNull() {
            addCriterion("CM_MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andCmMobileEqualTo(String value) {
            addCriterion("CM_MOBILE =", value, "cmMobile");
            return (Criteria) this;
        }

        public Criteria andCmMobileNotEqualTo(String value) {
            addCriterion("CM_MOBILE <>", value, "cmMobile");
            return (Criteria) this;
        }

        public Criteria andCmMobileGreaterThan(String value) {
            addCriterion("CM_MOBILE >", value, "cmMobile");
            return (Criteria) this;
        }

        public Criteria andCmMobileGreaterThanOrEqualTo(String value) {
            addCriterion("CM_MOBILE >=", value, "cmMobile");
            return (Criteria) this;
        }

        public Criteria andCmMobileLessThan(String value) {
            addCriterion("CM_MOBILE <", value, "cmMobile");
            return (Criteria) this;
        }

        public Criteria andCmMobileLessThanOrEqualTo(String value) {
            addCriterion("CM_MOBILE <=", value, "cmMobile");
            return (Criteria) this;
        }

        public Criteria andCmMobileLike(String value) {
            addCriterion("CM_MOBILE like", value, "cmMobile");
            return (Criteria) this;
        }

        public Criteria andCmMobileNotLike(String value) {
            addCriterion("CM_MOBILE not like", value, "cmMobile");
            return (Criteria) this;
        }

        public Criteria andCmMobileIn(List<String> values) {
            addCriterion("CM_MOBILE in", values, "cmMobile");
            return (Criteria) this;
        }

        public Criteria andCmMobileNotIn(List<String> values) {
            addCriterion("CM_MOBILE not in", values, "cmMobile");
            return (Criteria) this;
        }

        public Criteria andCmMobileBetween(String value1, String value2) {
            addCriterion("CM_MOBILE between", value1, value2, "cmMobile");
            return (Criteria) this;
        }

        public Criteria andCmMobileNotBetween(String value1, String value2) {
            addCriterion("CM_MOBILE not between", value1, value2, "cmMobile");
            return (Criteria) this;
        }

        public Criteria andAreaCodesIsNull() {
            addCriterion("AREA_CODES is null");
            return (Criteria) this;
        }

        public Criteria andAreaCodesIsNotNull() {
            addCriterion("AREA_CODES is not null");
            return (Criteria) this;
        }

        public Criteria andAreaCodesEqualTo(String value) {
            addCriterion("AREA_CODES =", value, "areaCodes");
            return (Criteria) this;
        }

        public Criteria andAreaCodesNotEqualTo(String value) {
            addCriterion("AREA_CODES <>", value, "areaCodes");
            return (Criteria) this;
        }

        public Criteria andAreaCodesGreaterThan(String value) {
            addCriterion("AREA_CODES >", value, "areaCodes");
            return (Criteria) this;
        }

        public Criteria andAreaCodesGreaterThanOrEqualTo(String value) {
            addCriterion("AREA_CODES >=", value, "areaCodes");
            return (Criteria) this;
        }

        public Criteria andAreaCodesLessThan(String value) {
            addCriterion("AREA_CODES <", value, "areaCodes");
            return (Criteria) this;
        }

        public Criteria andAreaCodesLessThanOrEqualTo(String value) {
            addCriterion("AREA_CODES <=", value, "areaCodes");
            return (Criteria) this;
        }

        public Criteria andAreaCodesLike(String value) {
            addCriterion("AREA_CODES like", value, "areaCodes");
            return (Criteria) this;
        }

        public Criteria andAreaCodesNotLike(String value) {
            addCriterion("AREA_CODES not like", value, "areaCodes");
            return (Criteria) this;
        }

        public Criteria andAreaCodesIn(List<String> values) {
            addCriterion("AREA_CODES in", values, "areaCodes");
            return (Criteria) this;
        }

        public Criteria andAreaCodesNotIn(List<String> values) {
            addCriterion("AREA_CODES not in", values, "areaCodes");
            return (Criteria) this;
        }

        public Criteria andAreaCodesBetween(String value1, String value2) {
            addCriterion("AREA_CODES between", value1, value2, "areaCodes");
            return (Criteria) this;
        }

        public Criteria andAreaCodesNotBetween(String value1, String value2) {
            addCriterion("AREA_CODES not between", value1, value2, "areaCodes");
            return (Criteria) this;
        }

        public Criteria andAreaNamesIsNull() {
            addCriterion("AREA_NAMES is null");
            return (Criteria) this;
        }

        public Criteria andAreaNamesIsNotNull() {
            addCriterion("AREA_NAMES is not null");
            return (Criteria) this;
        }

        public Criteria andAreaNamesEqualTo(String value) {
            addCriterion("AREA_NAMES =", value, "areaNames");
            return (Criteria) this;
        }

        public Criteria andAreaNamesNotEqualTo(String value) {
            addCriterion("AREA_NAMES <>", value, "areaNames");
            return (Criteria) this;
        }

        public Criteria andAreaNamesGreaterThan(String value) {
            addCriterion("AREA_NAMES >", value, "areaNames");
            return (Criteria) this;
        }

        public Criteria andAreaNamesGreaterThanOrEqualTo(String value) {
            addCriterion("AREA_NAMES >=", value, "areaNames");
            return (Criteria) this;
        }

        public Criteria andAreaNamesLessThan(String value) {
            addCriterion("AREA_NAMES <", value, "areaNames");
            return (Criteria) this;
        }

        public Criteria andAreaNamesLessThanOrEqualTo(String value) {
            addCriterion("AREA_NAMES <=", value, "areaNames");
            return (Criteria) this;
        }

        public Criteria andAreaNamesLike(String value) {
            addCriterion("AREA_NAMES like", value, "areaNames");
            return (Criteria) this;
        }

        public Criteria andAreaNamesNotLike(String value) {
            addCriterion("AREA_NAMES not like", value, "areaNames");
            return (Criteria) this;
        }

        public Criteria andAreaNamesIn(List<String> values) {
            addCriterion("AREA_NAMES in", values, "areaNames");
            return (Criteria) this;
        }

        public Criteria andAreaNamesNotIn(List<String> values) {
            addCriterion("AREA_NAMES not in", values, "areaNames");
            return (Criteria) this;
        }

        public Criteria andAreaNamesBetween(String value1, String value2) {
            addCriterion("AREA_NAMES between", value1, value2, "areaNames");
            return (Criteria) this;
        }

        public Criteria andAreaNamesNotBetween(String value1, String value2) {
            addCriterion("AREA_NAMES not between", value1, value2, "areaNames");
            return (Criteria) this;
        }

        public Criteria andBranchOfficeIsNull() {
            addCriterion("BRANCH_OFFICE is null");
            return (Criteria) this;
        }

        public Criteria andBranchOfficeIsNotNull() {
            addCriterion("BRANCH_OFFICE is not null");
            return (Criteria) this;
        }

        public Criteria andBranchOfficeEqualTo(String value) {
            addCriterion("BRANCH_OFFICE =", value, "branchOffice");
            return (Criteria) this;
        }

        public Criteria andBranchOfficeNotEqualTo(String value) {
            addCriterion("BRANCH_OFFICE <>", value, "branchOffice");
            return (Criteria) this;
        }

        public Criteria andBranchOfficeGreaterThan(String value) {
            addCriterion("BRANCH_OFFICE >", value, "branchOffice");
            return (Criteria) this;
        }

        public Criteria andBranchOfficeGreaterThanOrEqualTo(String value) {
            addCriterion("BRANCH_OFFICE >=", value, "branchOffice");
            return (Criteria) this;
        }

        public Criteria andBranchOfficeLessThan(String value) {
            addCriterion("BRANCH_OFFICE <", value, "branchOffice");
            return (Criteria) this;
        }

        public Criteria andBranchOfficeLessThanOrEqualTo(String value) {
            addCriterion("BRANCH_OFFICE <=", value, "branchOffice");
            return (Criteria) this;
        }

        public Criteria andBranchOfficeLike(String value) {
            addCriterion("BRANCH_OFFICE like", value, "branchOffice");
            return (Criteria) this;
        }

        public Criteria andBranchOfficeNotLike(String value) {
            addCriterion("BRANCH_OFFICE not like", value, "branchOffice");
            return (Criteria) this;
        }

        public Criteria andBranchOfficeIn(List<String> values) {
            addCriterion("BRANCH_OFFICE in", values, "branchOffice");
            return (Criteria) this;
        }

        public Criteria andBranchOfficeNotIn(List<String> values) {
            addCriterion("BRANCH_OFFICE not in", values, "branchOffice");
            return (Criteria) this;
        }

        public Criteria andBranchOfficeBetween(String value1, String value2) {
            addCriterion("BRANCH_OFFICE between", value1, value2, "branchOffice");
            return (Criteria) this;
        }

        public Criteria andBranchOfficeNotBetween(String value1, String value2) {
            addCriterion("BRANCH_OFFICE not between", value1, value2, "branchOffice");
            return (Criteria) this;
        }

        public Criteria andCmRoleIsNull() {
            addCriterion("CM_ROLE is null");
            return (Criteria) this;
        }

        public Criteria andCmRoleIsNotNull() {
            addCriterion("CM_ROLE is not null");
            return (Criteria) this;
        }

        public Criteria andCmRoleEqualTo(String value) {
            addCriterion("CM_ROLE =", value, "cmRole");
            return (Criteria) this;
        }

        public Criteria andCmRoleNotEqualTo(String value) {
            addCriterion("CM_ROLE <>", value, "cmRole");
            return (Criteria) this;
        }

        public Criteria andCmRoleGreaterThan(String value) {
            addCriterion("CM_ROLE >", value, "cmRole");
            return (Criteria) this;
        }

        public Criteria andCmRoleGreaterThanOrEqualTo(String value) {
            addCriterion("CM_ROLE >=", value, "cmRole");
            return (Criteria) this;
        }

        public Criteria andCmRoleLessThan(String value) {
            addCriterion("CM_ROLE <", value, "cmRole");
            return (Criteria) this;
        }

        public Criteria andCmRoleLessThanOrEqualTo(String value) {
            addCriterion("CM_ROLE <=", value, "cmRole");
            return (Criteria) this;
        }

        public Criteria andCmRoleLike(String value) {
            addCriterion("CM_ROLE like", value, "cmRole");
            return (Criteria) this;
        }

        public Criteria andCmRoleNotLike(String value) {
            addCriterion("CM_ROLE not like", value, "cmRole");
            return (Criteria) this;
        }

        public Criteria andCmRoleIn(List<String> values) {
            addCriterion("CM_ROLE in", values, "cmRole");
            return (Criteria) this;
        }

        public Criteria andCmRoleNotIn(List<String> values) {
            addCriterion("CM_ROLE not in", values, "cmRole");
            return (Criteria) this;
        }

        public Criteria andCmRoleBetween(String value1, String value2) {
            addCriterion("CM_ROLE between", value1, value2, "cmRole");
            return (Criteria) this;
        }

        public Criteria andCmRoleNotBetween(String value1, String value2) {
            addCriterion("CM_ROLE not between", value1, value2, "cmRole");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated do_not_delete_during_merge Wed May 10 19:32:17 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}