package com.lp.entity;

import java.util.Date;

public class LfucCustManager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LFUC_CUSTMANAGER.ID
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LFUC_CUSTMANAGER.CM_NO
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    private String cmNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LFUC_CUSTMANAGER.CM_NAME
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    private String cmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LFUC_CUSTMANAGER.CM_PWD
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    private String cmPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LFUC_CUSTMANAGER.CM_MOBILE
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    private String cmMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LFUC_CUSTMANAGER.AREA_CODES
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    private String areaCodes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LFUC_CUSTMANAGER.AREA_NAMES
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    private String areaNames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LFUC_CUSTMANAGER.BRANCH_OFFICE
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    private String branchOffice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LFUC_CUSTMANAGER.CM_ROLE
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    private String cmRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LFUC_CUSTMANAGER.STATUS
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LFUC_CUSTMANAGER.CREATE_TIME
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LFUC_CUSTMANAGER.UPDATE_TIME
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LFUC_CUSTMANAGER.ID
     *
     * @return the value of LFUC_CUSTMANAGER.ID
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LFUC_CUSTMANAGER.ID
     *
     * @param id the value for LFUC_CUSTMANAGER.ID
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LFUC_CUSTMANAGER.CM_NO
     *
     * @return the value of LFUC_CUSTMANAGER.CM_NO
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public String getCmNo() {
        return cmNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LFUC_CUSTMANAGER.CM_NO
     *
     * @param cmNo the value for LFUC_CUSTMANAGER.CM_NO
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public void setCmNo(String cmNo) {
        this.cmNo = cmNo == null ? null : cmNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LFUC_CUSTMANAGER.CM_NAME
     *
     * @return the value of LFUC_CUSTMANAGER.CM_NAME
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public String getCmName() {
        return cmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LFUC_CUSTMANAGER.CM_NAME
     *
     * @param cmName the value for LFUC_CUSTMANAGER.CM_NAME
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public void setCmName(String cmName) {
        this.cmName = cmName == null ? null : cmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LFUC_CUSTMANAGER.CM_PWD
     *
     * @return the value of LFUC_CUSTMANAGER.CM_PWD
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public String getCmPwd() {
        return cmPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LFUC_CUSTMANAGER.CM_PWD
     *
     * @param cmPwd the value for LFUC_CUSTMANAGER.CM_PWD
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public void setCmPwd(String cmPwd) {
        this.cmPwd = cmPwd == null ? null : cmPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LFUC_CUSTMANAGER.CM_MOBILE
     *
     * @return the value of LFUC_CUSTMANAGER.CM_MOBILE
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public String getCmMobile() {
        return cmMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LFUC_CUSTMANAGER.CM_MOBILE
     *
     * @param cmMobile the value for LFUC_CUSTMANAGER.CM_MOBILE
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public void setCmMobile(String cmMobile) {
        this.cmMobile = cmMobile == null ? null : cmMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LFUC_CUSTMANAGER.AREA_CODES
     *
     * @return the value of LFUC_CUSTMANAGER.AREA_CODES
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public String getAreaCodes() {
        return areaCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LFUC_CUSTMANAGER.AREA_CODES
     *
     * @param areaCodes the value for LFUC_CUSTMANAGER.AREA_CODES
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public void setAreaCodes(String areaCodes) {
        this.areaCodes = areaCodes == null ? null : areaCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LFUC_CUSTMANAGER.AREA_NAMES
     *
     * @return the value of LFUC_CUSTMANAGER.AREA_NAMES
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public String getAreaNames() {
        return areaNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LFUC_CUSTMANAGER.AREA_NAMES
     *
     * @param areaNames the value for LFUC_CUSTMANAGER.AREA_NAMES
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public void setAreaNames(String areaNames) {
        this.areaNames = areaNames == null ? null : areaNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LFUC_CUSTMANAGER.BRANCH_OFFICE
     *
     * @return the value of LFUC_CUSTMANAGER.BRANCH_OFFICE
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public String getBranchOffice() {
        return branchOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LFUC_CUSTMANAGER.BRANCH_OFFICE
     *
     * @param branchOffice the value for LFUC_CUSTMANAGER.BRANCH_OFFICE
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public void setBranchOffice(String branchOffice) {
        this.branchOffice = branchOffice == null ? null : branchOffice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LFUC_CUSTMANAGER.CM_ROLE
     *
     * @return the value of LFUC_CUSTMANAGER.CM_ROLE
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public String getCmRole() {
        return cmRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LFUC_CUSTMANAGER.CM_ROLE
     *
     * @param cmRole the value for LFUC_CUSTMANAGER.CM_ROLE
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public void setCmRole(String cmRole) {
        this.cmRole = cmRole == null ? null : cmRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LFUC_CUSTMANAGER.STATUS
     *
     * @return the value of LFUC_CUSTMANAGER.STATUS
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LFUC_CUSTMANAGER.STATUS
     *
     * @param status the value for LFUC_CUSTMANAGER.STATUS
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LFUC_CUSTMANAGER.CREATE_TIME
     *
     * @return the value of LFUC_CUSTMANAGER.CREATE_TIME
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LFUC_CUSTMANAGER.CREATE_TIME
     *
     * @param createTime the value for LFUC_CUSTMANAGER.CREATE_TIME
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LFUC_CUSTMANAGER.UPDATE_TIME
     *
     * @return the value of LFUC_CUSTMANAGER.UPDATE_TIME
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LFUC_CUSTMANAGER.UPDATE_TIME
     *
     * @param updateTime the value for LFUC_CUSTMANAGER.UPDATE_TIME
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}