package com.lp.mapper;

import com.lp.entity.LfucCustManager;
import com.lp.entity.LfucCustManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LfucCustManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    int countByExample(LfucCustManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    int deleteByExample(LfucCustManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    int insert(LfucCustManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    int insertSelective(LfucCustManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    List<LfucCustManager> selectByExample(LfucCustManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    LfucCustManager selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") LfucCustManager record, @Param("example") LfucCustManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    int updateByExample(@Param("record") LfucCustManager record, @Param("example") LfucCustManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    int updateByPrimaryKeySelective(LfucCustManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LFUC_CUSTMANAGER
     *
     * @mbggenerated Wed May 10 19:32:17 CST 2017
     */
    int updateByPrimaryKey(LfucCustManager record);
}